baseURL = "https://resume.marcusv.me"
languageCode = "en-us"
title = "Marcus Virginia"
theme = "hugo-resume"

[params]
    firstName = "Marcus"
    lastName = "Virginia"
    address = "Minneapolis, MN"
    phone = "1-218-591-0657"
    contactNote = "Web Developer/Engineer"
    profileImage = "img/pot1.jpg"
    email = "marcusvirg@yahoo.com"
    description = "Student & Aspiring Web Developer with experience building usable, creative web apps and programs."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = true
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = false

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/marcus-virginia-99ba35140/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/MarcusVirg"

[[params.handles]]
    name = "Instagram"
    link = "https://www.instagram.com/marcusv345/"
    icon = "instagram"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/8907736/marcus-virginia"
    icon = "stack-overflow"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/MarcusVirg"
    icon = "twitter"

[params.google.analytics]
    trackerID = "UA-108580096-3"
